# Generated by Django 4.1.6 on 2023-02-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='кличка')),
                ('age', models.PositiveIntegerField(verbose_name='возраст')),
                ('arrival_date', models.DateTimeField(auto_now_add=True, verbose_name='дата прибытия в приют')),
                ('weight', models.PositiveIntegerField(verbose_name='вес')),
                ('height', models.PositiveIntegerField(verbose_name='рост')),
                ('additional_information', models.TextField(blank=True, max_length=1000, null=True, verbose_name='дополнительная информация')),
            ],
            options={
                'verbose_name': 'животные',
                'verbose_name_plural': 'животное',
                'ordering': ['arrival_date'],
            },
        ),
    ]
