# Generated by Django 4.1.6 on 2023-02-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['arrival_date'], 'verbose_name': 'животное', 'verbose_name_plural': 'животные'},
        ),
        migrations.AddField(
            model_name='animal',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='запись удалена'),
        ),
    ]
